version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    depends_on:
      - db
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:14
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
